name: postgresql2
version: 0.2.14+3
author: Greg Lowe <greg@vis.net.nz>
description: >
  A temporary fork from xxgreg/postgresql for aggressive and probabaly unstable
  support of timestamptz and json. Will be merged back once Greg supports it
  officially.
homepage: https://github.com/xxgreg/postgresql
environment:
  sdk: ">=0.8.10+6 <2.0.0"
dependencies:
  crypto: ">=0.9.0 <0.10.0"
dev_dependencies:
  unittest: ">=0.9.0 <0.10.0"
  yaml: ">=0.9.0 <0.10.0"
