name: postgresql2
version: 0.2.14+7
author: Greg Lowe <greg@vis.net.nz>
description: >
  A temporary fork of Greg's PostgreSQL driver (xxgreg/postgresql)
  for aggressive and probably unstable support of timestamptz and JSON.
homepage: https://github.com/tomyeh/postgresql
environment:
  sdk: ">=0.8.10+6 <2.0.0"
dependencies:
  crypto: ">=0.9.0 <1.0.0"
dev_dependencies:
  test: ">=0.9.0 <2.0.0"
